spring:
  application:
    name: interviewpanel-ms-questionandanswer-service
  cloud:
     stream:
       kafka:
         binder:
           brokers:
           - http://localhost:9092
       bindings:
         output:
           destination: NEW_QUESTIONS_POSTED_TOPIC
server:
  port: 8082

management:
  endpoints:
    web: 
      exposure:
        include: '*'
  security:
    enabled: false